import { useState } from "react";
import copy from "copy-to-clipboard";

const Index = () => {
  const [videoURL, setVideoURL] = useState("");
  const [thumbnailOptions, setThumbnailOptions] = useState([]);

  const getYouTubeThumbnail = (url) => {
    let regExp = /.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#\&\?]*).*/;
    let match = url.match(regExp);

    if (match && match[1].length === 11) {
      const videoURL = match[1];
      const thumbnailBaseUrl = "http://img.youtube.com/vi/";

      const options = [
        { resolution: "HD (1280x720)", code: "maxresdefault" },
        { resolution: "SD (640x480)", code: "sddefault" },
        { resolution: "Normal (480x360)", code: "hqdefault" },
        { resolution: "Medium (320x180)", code: "mqdefault" },
        { resolution: "Low (120x90)", code: "default" },
      ];

      const thumbnailOptions = options.map((option) => ({
        resolution: option.resolution,
        url: `${thumbnailBaseUrl}${videoURL}/${option.code}.jpg`,
      }));

      setThumbnailOptions(thumbnailOptions);
      setVideoURL("");
    } else {
      setThumbnailOptions([]);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <header className="mb-8" style={{ width: '47%' }}>
        <h1 className="text-3xl font-bold mb-2">
          Free YouTube Thumbnail Downloader - High Quality, 4K, HD Thumbnails
        </h1>
        <p className="text-gray-700">
          Elevate Your Content with High-Resolution YouTube Video Thumbnails!
        </p>
        <p className="text-gray-700">
          YouTube Thumbnail Downloader is a free online tool that allows you to easily download YouTube video thumbnails in different sizes and qualities. All you need to do is copy a YouTube Video link, paste it in the given input box, and then press "Download YouTube Thumbnail" Your Thumbnail is ready to be downloaded in HD quality. You can also view the sample of the your YouTube video thumbnail. It supports all YouTube videos including 8K, 4K, 1080p, HD, HQ, etc.
        </p>
      </header>

      <div className="max-w-xl">
        <div className="flex flex-col items-center">
          <input
            type="text"
            className="w-full md:w-1/2 px-4 py-2 border rounded"
            placeholder="Enter YouTube URL"
            value={videoURL}
            onChange={(e) => setVideoURL(e.target.value)}
          />
          <button
            className="btn-blue mt-2"
            style={{ fontSize: '16px', backgroundColor: '#FF5733', borderRadius: '8px' }}
            onClick={() => getYouTubeThumbnail(videoURL)}
          >
            Download YouTube Thumbnail
          </button>
        </div>
      </div>

      {thumbnailOptions.length > 0 && (
        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">Thumbnail Options</h2>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {thumbnailOptions.map((option, index) => (
              <div key={index} className="thumbnail-option">
                <img src={option.url} alt={`Thumbnail ${index + 1}`} />
                <button
                  className="btn-blue mt-2"
                  onClick={() => copy(option.url)}
                >
                  Copy Image URL
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
<div className="mt-8">
        <h2 className="text-xl font-semibold mb-4">About YT Thumbnail Downloader</h2>
        <p className="text-gray-700">
        Our YT (YouTube Thumbnail) Downloader is a powerful tool that allows you to efficiently "Get Youtube Thumbnail js" without the need for any installations. It's completely "free download" for anyone looking to "get youtube thumbnail from URL".
        </p>
        <h2 className="text-xl font-semibold mb-4">Understanding YouTube Thumbnails</h2>
        <p className="text-gray-700">
        A YouTube thumbnail is a crucial element - it serves as a preview image for a video. Whether automatically generated by YouTube or custom ones "uploaded by the creator", it's important to know that their URLs are not publicly accessible on YouTube.
        </p>

        <h2 className="text-xl font-semibold mb-4">How Many Thumbnails Does a YouTube Video Have?</h2>
        <p className="text-gray-700">
        A YouTube video can potentially have up to nine thumbnails, with seven guaranteed sizes such as "Player Background 480x360", "Start 120x90", and more. For high-definition videos, additional sizes like "Standard Definition 640x480" and "Maximum Resolution 1920x1080" are available. Most commonly, users opt for "High-Quality", "Medium Quality", or full-size thumbnails, which our "yt thumbnail download" tool supports.
        </p>
        

        <h2 className="text-xl font-semibold mb-4">Why Download Thumbnails?</h2>
        <p className="text-gray-700">
        YouTube video thumbnails are crucial metadata—they provide a visual preview of the video's content. Many creators design these covers meticulously, resulting in visually appealing and intriguing thumbnails. Users download them for purposes like setting wallpapers, sharing on blogs or social media, or as inspiration for their own video covers.
        </p>

        <h2 className="text-xl font-semibold mb-4">Why Use a Thumbnail Downloader?</h2>
        <p className="text-gray-700">
        YouTube video thumbnails are crucial metadata—they provide a visual preview of the video's content. Many creators design these covers meticulously, resulting in visually appealing and intriguing thumbnails. Users download them for purposes like setting wallpapers, sharing on blogs or social media, or as inspiration for their own videoUnlike other methods, our YouTube Thumbnail Downloader simplifies the process. It provides a straightforward way to access and save video covers. covers.
        </p>

        <h2 className="text-xl font-semibold mb-4">How to Use the YT Thumbnail Downloader:</h2>
        <p className="text-gray-700">
        Copy and paste the video URL into the search box above.
The YT Thumbnail Downloader will automatically retrieve three different thumbnail sizes.
Select your preferred thumbnail for download. We recommend HD thumbnails.
        </p>

        <h2 className="text-xl font-semibold mb-4">Obtaining Different Thumbnail Sizes:</h2>
        <p className="text-gray-700">
        For those interested in all thumbnail sizes, you'll need to understand the video ID. This unique identifier is part of the video URL. Here's a list of thumbnail image links, along with the placeholders for the video ID:

        480x360: [Link]
        120x90 [Link]
        120x90: [Link]
        120x90: [Link]
        480x360: [Link]
        320x180: [Link]
        20x90: [Link]
      640x480: [Link]
      1920x1080: [Link]
Please note that this method may be complex. If you don't require additional thumbnail sizes, our Thumbnail Downloader simplifies the process.
        </p>

        <h2 className="text-xl font-semibold mb-4">Using Downloaded Thumbnails on YouTube:</h2>
        <p className="text-gray-700">
        Remember, the copyright for a thumbnail belongs to the creator or designer. Using thumbnails without permission can lead to reporting and legal action. We advise against copying others' thumbnails. Instead, they can serve as inspiration for your own designs.
        </p>



      

        </div>
      </div>
  
  );
};

export default Index;
